//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.MiscResources", typeof(MiscResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال کسب اطلاعات ....
        /// </summary>
        internal static string AcquiringData {
            get {
                return ResourceManager.GetString("AcquiringData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات در حال پیشرفت.
        /// </summary>
        internal static string ActiveOperations {
            get {
                return ResourceManager.GetString("ActiveOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        internal static string AllCount {
            get {
                return ResourceManager.GetString("AllCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام تلاش برای تأیید خطایی روی داد..
        /// </summary>
        internal static string AuthError {
            get {
                return ResourceManager.GetString("AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deskewing....
        /// </summary>
        internal static string AutoDeskewing {
            get {
                return ResourceManager.GetString("AutoDeskewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deskew پیشرفت.
        /// </summary>
        internal static string AutoDeskewProgress {
            get {
                return ResourceManager.GetString("AutoDeskewProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام تلاش برای ذخیره خودکار خطایی روی داد..
        /// </summary>
        internal static string AutoSaveError {
            get {
                return ResourceManager.GetString("AutoSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام اسکن دسته ای یک خطای ناشناخته رخ داده است..
        /// </summary>
        internal static string BatchError {
            get {
                return ResourceManager.GetString("BatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته لغو شد.
        /// </summary>
        internal static string BatchStatusCancelled {
            get {
                return ResourceManager.GetString("BatchStatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال لغو ....
        /// </summary>
        internal static string BatchStatusCancelling {
            get {
                return ResourceManager.GetString("BatchStatusCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته با موفقیت انجام شد.
        /// </summary>
        internal static string BatchStatusComplete {
            get {
                return ResourceManager.GetString("BatchStatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکن دسته ای به دلیل خطا متوقف شد..
        /// </summary>
        internal static string BatchStatusError {
            get {
                return ResourceManager.GetString("BatchStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال اسکن صفحه {0} ....
        /// </summary>
        internal static string BatchStatusPage {
            get {
                return ResourceManager.GetString("BatchStatusPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ذخیره نتایج دسته ای ....
        /// </summary>
        internal static string BatchStatusSaving {
            get {
                return ResourceManager.GetString("BatchStatusSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال اسکن صفحه {0} (اسکن {1}) ....
        /// </summary>
        internal static string BatchStatusScanPage {
            get {
                return ResourceManager.GetString("BatchStatusScanPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار اسکن {0} ....
        /// </summary>
        internal static string BatchStatusWaitingForScan {
            get {
                return ResourceManager.GetString("BatchStatusWaitingForScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو دسته.
        /// </summary>
        internal static string CancelBatch {
            get {
                return ResourceManager.GetString("CancelBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بررسی ....
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایه را انتخاب کنید.
        /// </summary>
        internal static string ChooseProfile {
            get {
                return ResourceManager.GetString("ChooseProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاک کردن.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید اسکن دسته ای را لغو کنید؟.
        /// </summary>
        internal static string ConfirmCancelBatch {
            get {
                return ResourceManager.GetString("ConfirmCancelBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید {0} مورد را پاک کنید؟.
        /// </summary>
        internal static string ConfirmClearItems {
            get {
                return ResourceManager.GetString("ConfirmClearItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید &quot;{0}&quot; را حذف کنید؟.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید {0} مورد را حذف کنید؟.
        /// </summary>
        internal static string ConfirmDeleteItems {
            get {
                return ResourceManager.GetString("ConfirmDeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید {0} نمایه را حذف کنید؟.
        /// </summary>
        internal static string ConfirmDeleteMultipleProfiles {
            get {
                return ResourceManager.GetString("ConfirmDeleteMultipleProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید نمایه {0} را حذف کنید؟.
        /// </summary>
        internal static string ConfirmDeleteSingleProfile {
            get {
                return ResourceManager.GetString("ConfirmDeleteSingleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرونده {0} از قبل وجود دارد. آیا می خواهید آن را بازنویسی کنید؟.
        /// </summary>
        internal static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید تغییرات خود را در {0} تصویر لغو کنید؟.
        /// </summary>
        internal static string ConfirmResetImages {
            get {
                return ResourceManager.GetString("ConfirmResetImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال کپی کردن ....
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت کپی کردن.
        /// </summary>
        internal static string CopyProgress {
            get {
                return ResourceManager.GetString("CopyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارشی ({0} x {1} {2}).
        /// </summary>
        internal static string CustomPageSizeFormat {
            get {
                return ResourceManager.GetString("CustomPageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر انتخاب شده مشغول است..
        /// </summary>
        internal static string DeviceBusy {
            get {
                return ResourceManager.GetString("DeviceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درپوش اسکنر باز است..
        /// </summary>
        internal static string DeviceCoverOpen {
            get {
                return ResourceManager.GetString("DeviceCoverOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر انتخاب شده یافت نشد..
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر انتخاب شده آفلاین است..
        /// </summary>
        internal static string DeviceOffline {
            get {
                return ResourceManager.GetString("DeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر یک مربع کاغذ دارد..
        /// </summary>
        internal static string DevicePaperJam {
            get {
                return ResourceManager.GetString("DevicePaperJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر در حال گرم شدن است..
        /// </summary>
        internal static string DeviceWarmingUp {
            get {
                return ResourceManager.GetString("DeviceWarmingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAPS2 is completely free. Consider making a donation..
        /// </summary>
        internal static string DonatePrompt {
            get {
                return ResourceManager.GetString("DonatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه ذخیره پرونده در این مکان را ندارید..
        /// </summary>
        internal static string DontHavePermission {
            get {
                return ResourceManager.GetString("DontHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بارگیری.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگیری مورد نیاز.
        /// </summary>
        internal static string DownloadNeeded {
            get {
                return ResourceManager.GetString("DownloadNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درایور انتخاب شده در این سیستم پشتیبانی نمی شود..
        /// </summary>
        internal static string DriverNotSupported {
            get {
                return ResourceManager.GetString("DriverNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام تلاش برای ارسال ایمیل خطایی روی داد..
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل PDF.
        /// </summary>
        internal static string EmailPdf {
            get {
                return ResourceManager.GetString("EmailPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت ارسال ایمیل PDF.
        /// </summary>
        internal static string EmailPdfProgress {
            get {
                return ResourceManager.GetString("EmailPdfProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام تلاش برای ارسال ایمیل خطایی روی داد..
        /// </summary>
        internal static string ErrorEmailing {
            get {
                return ResourceManager.GetString("ErrorEmailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام تلاش برای ذخیره فایل ، خطایی روی داد..
        /// </summary>
        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم تخمینی بارگیری: {0} مگابایت.
        /// </summary>
        internal static string EstimatedDownloadSize {
            get {
                return ResourceManager.GetString("EstimatedDownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیاتی در حال انجام است. آیا مطمئن هستید که می خواهید از این عملیات خارج شوید و آن را لغو کنید؟.
        /// </summary>
        internal static string ExitWithActiveOperations {
            get {
                return ResourceManager.GetString("ExitWithActiveOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما تغییرات ذخیره نشده ای دارید. آیا مطمئن هستید که می خواهید از آن تغییرات خارج شوید و آنها را کنار بگذارید؟.
        /// </summary>
        internal static string ExitWithUnsavedChanges {
            get {
                return ResourceManager.GetString("ExitWithUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان بازنویسی پرونده وجود ندارد زیرا اکنون در حال استفاده است..
        /// </summary>
        internal static string FileInUse {
            get {
                return ResourceManager.GetString("FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا چند پرونده بارگیری نمی شوند..
        /// </summary>
        internal static string FilesCouldNotBeDownloaded {
            get {
                return ResourceManager.GetString("FilesCouldNotBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} پرونده.
        /// </summary>
        internal static string FilesProgressFormat {
            get {
                return ResourceManager.GetString("FilesProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام فایل ها.
        /// </summary>
        internal static string FileTypeAllFiles {
            get {
                return ResourceManager.GetString("FileTypeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Files (*.bmp).
        /// </summary>
        internal static string FileTypeBmp {
            get {
                return ResourceManager.GetString("FileTypeBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Windows MetaFile (*.emf).
        /// </summary>
        internal static string FileTypeEmf {
            get {
                return ResourceManager.GetString("FileTypeEmf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchangeable Image File (*.exif).
        /// </summary>
        internal static string FileTypeExif {
            get {
                return ResourceManager.GetString("FileTypeExif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF File (*.gif).
        /// </summary>
        internal static string FileTypeGif {
            get {
                return ResourceManager.GetString("FileTypeGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاویر.
        /// </summary>
        internal static string FileTypeImageFiles {
            get {
                return ResourceManager.GetString("FileTypeImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG File (*.jpg, *.jpeg).
        /// </summary>
        internal static string FileTypeJpeg {
            get {
                return ResourceManager.GetString("FileTypeJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Document (*.pdf).
        /// </summary>
        internal static string FileTypePdf {
            get {
                return ResourceManager.GetString("FileTypePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File (*.png).
        /// </summary>
        internal static string FileTypePng {
            get {
                return ResourceManager.GetString("FileTypePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF File (*.tiff, *.tif).
        /// </summary>
        internal static string FileTypeTiff {
            get {
                return ResourceManager.GetString("FileTypeTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر ذخیره شد.
        /// </summary>
        internal static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تصویر ذخیره شد..
        /// </summary>
        internal static string ImagesSaved {
            get {
                return ResourceManager.GetString("ImagesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرونده &quot;{0}&quot; وارد نشد..
        /// </summary>
        internal static string ImportErrorCouldNot {
            get {
                return ResourceManager.GetString("ImportErrorCouldNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرونده &quot;{0}&quot; وارد نشد. فقط فایلهای PDF تولید شده توسط این برنامه قابل وارد شدن هستند..
        /// </summary>
        internal static string ImportErrorNAPS2Pdf {
            get {
                return ResourceManager.GetString("ImportErrorNAPS2Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن ....
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن {0} ....
        /// </summary>
        internal static string ImportingFormat {
            get {
                return ResourceManager.GetString("ImportingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت در وارد کردن.
        /// </summary>
        internal static string ImportProgress {
            get {
                return ResourceManager.GetString("ImportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب {0}.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب کامل شد.
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب کامل شد. آیا می خواهید برنامه را دوباره راه اندازی کنید؟.
        /// </summary>
        internal static string InstallCompletePromptRestart {
            get {
                return ResourceManager.GetString("InstallCompletePromptRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب انجام نشد..
        /// </summary>
        internal static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب انجام نشد.
        /// </summary>
        internal static string InstallFailedTitle {
            get {
                return ResourceManager.GetString("InstallFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گوش دادن به درگاه {0}.
        /// </summary>
        internal static string ListeningOnPort {
            get {
                return ResourceManager.GetString("ListeningOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}x{2} {3}).
        /// </summary>
        internal static string NamedPageSizeFormat {
            get {
                return ResourceManager.GetString("NamedPageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام موجود نیست.
        /// </summary>
        internal static string NameMissing {
            get {
                return ResourceManager.GetString("NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر اتوماسیون اداری رایورز.
        /// </summary>
        internal static string NAPS2 {
            get {
                return ResourceManager.GetString("NAPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرور اتوماسیون اداری رایورز.
        /// </summary>
        internal static string Naps2Server {
            get {
                return ResourceManager.GetString("Naps2Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاهی انتخاب نشده است..
        /// </summary>
        internal static string NoDeviceSelected {
            get {
                return ResourceManager.GetString("NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ دستگاهی برای اسکن یافت نشد..
        /// </summary>
        internal static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر انتخاب شده از دوبلکس پشتیبانی نمی کند. اگر قرار است اسکنر شما از دوبلکس پشتیبانی کند ، سعی کنید از درایور دیگری استفاده کنید..
        /// </summary>
        internal static string NoDuplexSupport {
            get {
                return ResourceManager.GetString("NoDuplexSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر انتخاب شده با استفاده از فیدر پشتیبانی نمی کند. اگر اسکنر شما فیدر دارد ، از درایور دیگری استفاده کنید..
        /// </summary>
        internal static string NoFeederSupport {
            get {
                return ResourceManager.GetString("NoFeederSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ صفحه ای در فیدر وجود ندارد..
        /// </summary>
        internal static string NoPagesInFeeder {
            get {
                return ResourceManager.GetString("NoPagesInFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ به روزرسانی در دسترس نیست.
        /// </summary>
        internal static string NoUpdates {
            get {
                return ResourceManager.GetString("NoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت OCR.
        /// </summary>
        internal static string OcrProgress {
            get {
                return ResourceManager.GetString("OcrProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روزرسانی OCR موجود است..
        /// </summary>
        internal static string OcrUpdateAvailable {
            get {
                return ResourceManager.GetString("OcrUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از {0}.
        /// </summary>
        internal static string OfN {
            get {
                return ResourceManager.GetString("OfN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنویسی پرونده.
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای وارد کردن این فایل PDF یک جز مولفه اضافی مورد نیاز است. آیا می خواهید آن را بارگیری کنید؟.
        /// </summary>
        internal static string PdfImportComponentNeeded {
            get {
                return ResourceManager.GetString("PdfImportComponentNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه کپی مطالب از پرونده &quot;{0}&quot; را ندارید..
        /// </summary>
        internal static string PdfNoPermissionToExtractContent {
            get {
                return ResourceManager.GetString("PdfNoPermissionToExtractContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF ذخیره شد.
        /// </summary>
        internal static string PdfSaved {
            get {
                return ResourceManager.GetString("PdfSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} از {1}.
        /// </summary>
        internal static string PdfStatus {
            get {
                return ResourceManager.GetString("PdfStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string ProgressFormat {
            get {
                return ResourceManager.GetString("ProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بازیابی ....
        /// </summary>
        internal static string Recovering {
            get {
                return ResourceManager.GetString("Recovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت بازیابی.
        /// </summary>
        internal static string RecoveryProgress {
            get {
                return ResourceManager.GetString("RecoveryProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم مجدد تصویر.
        /// </summary>
        internal static string ResetImage {
            get {
                return ResourceManager.GetString("ResetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال اجرا OCR ....
        /// </summary>
        internal static string RunningOcr {
            get {
                return ResourceManager.GetString("RunningOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درایور SANE در دسترس نیست. اطمینان حاصل کنید که بسته های مورد نیاز را نصب کنید:.
        /// </summary>
        internal static string SaneNotAvailable {
            get {
                return ResourceManager.GetString("SaneNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره تصویر.
        /// </summary>
        internal static string SaveImages {
            get {
                return ResourceManager.GetString("SaveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت ذخیره تصویر.
        /// </summary>
        internal static string SaveImagesProgress {
            get {
                return ResourceManager.GetString("SaveImagesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره PDF.
        /// </summary>
        internal static string SavePdf {
            get {
                return ResourceManager.GetString("SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت ذخیره PDF.
        /// </summary>
        internal static string SavePdfProgress {
            get {
                return ResourceManager.GetString("SavePdfProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ذخیره {0} ....
        /// </summary>
        internal static string SavingFormat {
            get {
                return ResourceManager.GetString("SavingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکن.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر اسکن شده.
        /// </summary>
        internal static string ScannedImage {
            get {
                return ResourceManager.GetString("ScannedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال اسکن صفحه {0}.
        /// </summary>
        internal static string ScanPageProgress {
            get {
                return ResourceManager.GetString("ScanPageProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال اسکن صفحه {0} ....
        /// </summary>
        internal static string ScanProgressPage {
            get {
                return ResourceManager.GetString("ScanProgressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب شده ({0}).
        /// </summary>
        internal static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبل از کلیک روی اسکن ، یک نمایه را انتخاب کنید..
        /// </summary>
        internal static string SelectProfileBeforeScan {
            get {
                return ResourceManager.GetString("SelectProfileBeforeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرور شروع شد.
        /// </summary>
        internal static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} MB.
        /// </summary>
        internal static string SizeProgress {
            get {
                return ResourceManager.GetString("SizeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موتور OCR موجود نیست. اطمینان حاصل کنید که بسته مورد نیاز را نصب کنید:.
        /// </summary>
        internal static string TesseractNotAvailable {
            get {
                return ResourceManager.GetString("TesseractNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در درایور اسکن رخ داده است..
        /// </summary>
        internal static string UnknownDriverError {
            get {
                return ResourceManager.GetString("UnknownDriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات ذخیره نشده.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روزرسانی موجود است.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام نصب به روزرسانی خطایی روی داد..
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفت را به روز کنید.
        /// </summary>
        internal static string UpdateProgress {
            get {
                return ResourceManager.GetString("UpdateProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بروز رسانی ....
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری ایمیل ....
        /// </summary>
        internal static string UploadingEmail {
            get {
                return ResourceManager.GetString("UploadingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نگارش {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
